name: pymol-oss
version: '2.5-master-7c931c89'
base: core22
summary: PyMOL is a molecular visualization system.
description: |
    PyMOL is computer software, a molecular visualization system created by Warren Lyford DeLano. It is user-sponsored,
    open-source software, released under the Python License. It was commercialized initially by DeLano Scientific LLC,
    which was a private software company dedicated to creating useful tools that become universally accessible to
    scientific and educational communities. It is currently commercialized by Schrödinger, Inc. PyMOL can produce
    high-quality 3D images of small molecules and biological macromolecules, such as proteins. According to the original
    author, by 2009, almost a quarter of all published images of 3D protein structures in the scientific literature were
    made using PyMOL.

    This is the Open Source version of PyMOL. The source code is availabe on GitHub:

    https://github.com/schrodinger/pymol-open-source

    The commercial version with additional features is available on "https://pymol.org".

architectures: 
  - amd64

icon: snap/gui/icon.svg

grade: stable
confinement: strict

compression: lzo

apps:
  pymol:
    extensions: [gnome]
    command-chain:
      - bin/desktop-launch
    command: usr/bin/pymol-oss
    environment:
      NO_AT_BRIDGE: 1
      DISABLE_WAYLAND: 1
      PYMOL_PATH: /snap/pymol-oss/current/usr/share/pymol
    plugs:
      - desktop
      - gsettings
      - home
      - network
      - opengl
      - removable-media
      - unity7
      - wayland
      - x11


layout:
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm


plugs:
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes


parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: [ "FLAVOR=qt5" ]
    stage-packages:
      - libqt5gui5
      - libqt5svg5
      - libxkbcommon0
      - shared-mime-info

  mmtf-cpp:
    plugin: cmake
    cmake-parameters: [-DCMAKE_INSTALL_PREFIX=/usr/]
    source-type: tar
    source: https://github.com/rcsb/mmtf-cpp/archive/v1.0.0.tar.gz
    build-packages:
      - build-essential
      - libmsgpack-dev    

  pymol-oss:
    plugin: python
    source-type: git
    source: https://github.com/schrodinger/pymol-open-source.git
    source-commit: 7c931c893a8a22eeeed915bec0c24cff52981eb0
    build-packages: 
      - libfreetype6-dev
      - libglew-dev
      - libglm-dev
      - libmsgpack-dev
      - libnetcdf-dev
      - libpng-dev
      - libpython3.10-dev
      - libsqlite3-dev
      - libxml2-dev
      - python3-numpy
    stage-packages:
      - ffmpeg
      - freeglut3
      - libglew2.2
      - libglu1-mesa
      - libnetcdf19
      - libqt5gui5
      - python3-cryptography
      - python3-numpy
      - python3-openssl
      - python3-pyqt5
      - python3-pyqt5.qtopengl
      - python3-socks
      - python3-tk
      - python3-urllib3
      - python3-xdg      
      - qtwayland5
    override-build: |
      for commit in `ls ${CRAFT_PROJECT_DIR}/local/patches`; do patch -p1 < ${CRAFT_PROJECT_DIR}/local/patches/$commit; done
      python3 setup.py --use-msgpackc c++11 install --home=/snap/pymol-oss/current/usr
      mv /snap/pymol-oss/current/usr/lib/python/pymol/pymol_path ${CRAFT_PART_INSTALL}/usr/share/pymol
      cp -r /snap/pymol-oss/current/usr ${CRAFT_PART_INSTALL}/
      mv ${CRAFT_PART_INSTALL}/usr/lib/python/* ${CRAFT_PART_INSTALL}/usr/lib/python3/dist-packages
      cp ${CRAFT_PROJECT_DIR}/local/launchers/pymol-oss ${CRAFT_PART_INSTALL}/usr/bin/pymol-oss
      chmod +x ${CRAFT_PART_INSTALL}/usr/bin/pymol-oss
      rm ${CRAFT_PART_INSTALL}/usr/bin/pymol
      rm -rf /snap/pymol-oss ${CRAFT_PART_INSTALL}/usr/lib/python  
    after: [desktop-qt5, mmtf-cpp]


